{% set name = "Orange3-Bioinformatics" %}
{% set version = "4.7.0" %}
{% set sha256 = "5bac9c05109717506bf9491c596a9750e8c7d81a6a1b092cf495d657e50f8acb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: true

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3
    - orange3
    - serverfiles
    - requests
    - requests-cache
    - genesis-pyapi
    - scipy
    - numpy
    - pyclipper
    - point-annotator

test:
  commands:
     # - pwd
     # - python -c "help('modules')"

  imports:
    - orangecontrib.bioinformatics

about:
  home: https://github.com/biolab/orange3-bioinformatics
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Orange3 add-on with common functionality for bioinformatics

  description: |
    Orange Bioinformatics provides access to publicly available data, 
    like GEO data sets, GO and KEGG. All features can be combined with 
    powerful visualization, network exploration and data mining techniques 
    from the Orange data mining framework.
  dev_url: https://github.com/biolab/orange3-bioinformatics

extra:
  recipe-maintainers:
    - jakakokosar
    - astaric
