{% set name = "Orange3-Bioinformatics" %}
{% set version = "3.2.0" %}
{% set sha256 = "cc97ff279c770d4395fa29b2dcb3ef7c233179efeedb855bebc6c9fa0904dcd0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  preserve_egg_dir: True

requirements:
  host:
    - python >=3
    - pip
    - setuptools

  run:
    - python >=3
    - orange3
    - serverfiles
    - requests
    - requests-cache
    - genesis-pyapi

test:
  imports:
    - orangecontrib.bioinformatics

about:
  home: https://github.com/biolab/orange3-bioinformatics
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Orange3 add-on with common functionality for bioinformatics'

  description: |
    Orange Bioinformatics provides access to publicly available data, 
    like GEO data sets, GO and KEGG. All features can be combined with 
    powerful visualization, network exploration and data mining techniques 
    from the Orange data mining framework.
  dev_url: https://github.com/biolab/orange3-bioinformatics

extra:
  recipe-maintainers:
    - jakakokosar
    - astaric
