travis:
  secure:
    BINSTAR_TOKEN: ckfo1UpY/yXVyDw+QGLSWXYNn4VsyuCniwstEi0/nQO27X2IrzSINAdpzKkf0saKMSsLiSz2GMWH2foAErBjY8a5DOJN+t004C4EepqjFxjYKCDzqKEAxbvtFK2exSbIQonaMKxZ9npQL8FB/8gBOQafqhrLFvClfv/U9u4rf/eiYu7oG7QCSVLdD0mfezSoalaxetw5y2AT9r5QCDVMNzT3MxgyK5g8XG6tLhOHflGc9BbZe+WQPNBaMBaj5pSdNYitppXwxCOtB1mRQWk1DMdtX6C8VI+y7BxrZ7lEYZDDE+0OE7xReW2A8zlzc4UNJMLCzcHYpTXQabZ8Q9Z/Vnppakdv5YeutoSjV5gzuX2DrJBuomiMiDk2KMkhrp1J0izRwH9J26AG4CtMMywCssqTnC/BNxt21cwZ3PCd2FlOC9MKLTsibmOfsBQ90gyh8xwQ09Fy0UnLnPJUdO/ELAi8G/eXUtv5FvTd+Guq0aAdfixiYtyBoD1MG/EMeVsTaTTztMuwNNU/yk/ZhHiN+vLYodTmJlJYfxylwfiXOiBqYc9eitkmWGFiTtR/N5Relv1gZ1+pZBOqc2h4tOg5qXsGEZwL78du8EYYHGhziaL4d7cDpCVnbrlUZLPEh6jdS2CtoMuMCLU8sp3LCF3R7i/wNXeSTHDwSFLaI77+7GA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
